---
apiVersion: extensions/v1beta1
description: Kubernetes Native Serverless Framework
kind: ThirdPartyResource
metadata:
  name: function.k8s.io
versions:
- name: v1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller-acct
  namespace: kubeless
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    kubeless: controller
  name: kubeless-controller
  namespace: kubeless
spec:
  selector:
    matchLabels:
      kubeless: controller
  template:
    metadata:
      labels:
        kubeless: controller
    spec:
      containers:
      - image: bitnami/kubeless-controller@sha256:719e032c351d1db448b941060db0d5a2a77da62c6e9f38d509d372c22f3021e8
        imagePullPolicy: IfNotPresent
        name: kubeless-controller
      serviceAccountName: controller-acct
